In [1]:
import pandas as pd

ESTE CODIGO LEE UN ARCHIVO CSV.
en este caso como se puede verificar en el csv. las categorias estan separdas por ',' y python lo entiende.

In [3]:
pd.read_csv('/content/bestsellers-with-categories.csv')

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

Para declarar un seprador especifico se utiliza el metodo sep  = 'seprador'. EN este caso lo dejameros en ',' porque asi esta en el archivo. La funcion header permite declarar en que fila estan los encabezados de cad columna, en este caso estan en la 0, pero es posible definir esto.

In [11]:
df_books = pd.read_csv('/content/bestsellers-with-categories.csv',sep=',',header = 0)
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [12]:
df_books.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

Para modificar o configurar los indices de las columnas se puede hacer asi:

In [13]:
pd.read_csv('/content/bestsellers-with-categories.csv',sep=',',header= 0, names=['Nameeeeees', 'Auuuuuthor', 'User Raaaating', 'Reviews', 'Price', 'Year', 'Genre'])

,Nameeeeees,Auuuuuthor,User Raaaating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

Para archivos de Json.

In [14]:
pd.read_json('/content/hpcharactersdataraw.json')

,Name,Link,Descr,Gender,Species/Race,Blood,School,Profession
0,Mrs. Abbott,https://www.hp-lexicon.org/character/abbott-fa...,"Mrs. Abbott was the mother of Hannah Abbott, a...",Female,Witch,Muggle-born,Unknown,Unknown
1,Hannah Abbott,https://www.hp-lexicon.org/character/abbott-fa...,Hannah Abbott is a Hufflepuff student in Harry...,Female,Witch,Half-blood,Hogwarts - Hufflepuff,Landlady of the Leaky Cauldron
2,Abel Treetops,https://www.hp-lexicon.org/character/abel-tree...,Abel Treetops was a wizard from Cincinnati who...,Male,Wizard,Unknown,Unknown,Unknown
3,Euan Abercrombie,https://www.hp-lexicon.org/character/abercromb...,Euan Abercrombie was a small boy with prominen...,Male,Wizard,Unknown,Hogwarts - Gryffindor,Unknown
4,Aberforth Dumbledore,https://www.hp-lexicon.org/character/dumbledor...,"Aberforth Dumbledore was a tall, thin, grumpy-...",Male,Wizard,Half-blood,Hogwarts - Student,Barman
...,...,...,...,...,...,...,...,...
1935,Georgi Zdravko,https://www.hp-lexicon.org/character/georgi-zd...,Georgi Zdravko played KeeperÂ for the Bulgarian...,Male,Wizard,Unknown,Unknown,Quidditch player (Seeker)
1936,Zograf,https://www.hp-lexicon.org/character/zograf/,Zograf played KeeperÂ for theÂ Bulgarian Nationa...,NaN,Wizard,Unknown,Unknown,Quidditch player (Keeper)
1937,Zonko,https://www.hp-lexicon.org/character/zonko/,Founder(?) of Zonkoâ€™s Joke Shop. Possibly a re...,NaN,Unknown,Unknown,Unknown,Unknown
1938,Valentina VÃ¡zquez,https://www.hp-lexicon.org/character/valentina...,Valentina VÃ¡zquez was President of the Argenti...,Female,Witch,Unknown,Unknown,President of the Argentinian Council of Magic
1939,Zygmunt Budge,https://www.hp-lexicon.org/character/zygmunt-b...,Zygmunt Budge is considered to be one of the m...,Male,Wizard,Unknown,Hogwarts - Student,"Potions Master, Potioneer, Inventor, Author"

Esto me genera un indice de cara diccionario especifico

In [15]:
pd.read_json('/content/hpcharactersdataraw.json',typ='Series')

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina VÃ¡zquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

Filtrando datos con loc y iloc

In [3]:
df_books = pd.read_csv('/content/bestsellers-with-categories.csv',sep=',',header=0)

In [20]:
df_books[0:4]

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction

In [4]:
df_books[['Name', 'Author','Year']]

,Name,Author,Year
0,10-Day Green Smoothie Cleanse,JJ Smith,2016
1,11/22/63: A Novel,Stephen King,2011
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,2018
3,1984 (Signet Classics),George Orwell,2017
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,2019
...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,2019
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2016
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2017
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2018
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2019

Pero ahora,  Â¿como hago para filtrar datos de una combinacion entre filas y columnas?. Para esto se utiliza *Loc*

In [5]:
df_books.loc[0:4]

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [6]:
df_books.loc[0:4, ['Name','Author']]

                                                Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [7]:
df_books.loc[:, ['Reviews']] *-1

     Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [8]:
df_books.loc[:, ['Author']] == 'JJ Smith'

     Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

Funcion Iloc

In [9]:
df_books.iloc[:]

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [10]:
df_books.iloc[:,0:3]

,Name,Author,User Rating
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7
1,11/22/63: A Novel,Stephen King,4.6
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7
3,1984 (Signet Classics),George Orwell,4.7
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8
...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7

In [11]:
df_books.iloc[1,3]*-1

-2052

In [13]:
df_books.iloc[:3,2:]

   User Rating  Reviews  Price  Year        Genre
0          4.7    17350      8  2016  Non Fiction
1          4.6     2052     22  2011      Fiction
2          4.7    18979     15  2018  Non Fiction